
export const TRANSLATIONS = {
  ar: {
    title: "محول كشوف الحضور اليدوية",
    subtitle: "تحويل كشوف الحضور المكتوبة بخط اليد إلى ملفات Excel ذكية",
    login: "تسجيل الدخول",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    upload: "رفع ملف",
    dashboard: "لوحة التحكم",
    status: "الحالة",
    date: "التاريخ",
    uploadedBy: "رفع بواسطة",
    actions: "الإجراءات",
    processing: "جاري المعالجة",
    completed: "مكتمل",
    failed: "فشل",
    noFiles: "لا يوجد ملفات مرفوعة بعد",
    dragDrop: "اسحب وأفلت الملف هنا أو انقر للاختيار",
    maxSize: "الحد الأقصى للملف: 20 ميجابايت",
    convertToDigital: "تحويل إلى بيانات رقمية",
    reviewEdit: "مراجعة وتعديل البيانات",
    downloadExcel: "تحميل ملف Excel",
    employeeName: "اسم الموظف",
    checkIn: "حضور",
    checkOut: "انصراف",
    saveChanges: "حفظ التعديلات",
    confidenceInfo: "الخلايا المظللة بالأحمر تعني دقة منخفضة، يرجى مراجعتها.",
    arabicDigits: "الأرقام العربية",
    englishInterface: "English Interface",
    arabicInterface: "واجهة عربية",
    manageDictionary: "قاموس الأسماء",
    dictionarySubtitle: "إضافة أسماء الموظفين لتحسين دقة التعرف الضوئي (OCR)",
    addName: "إضافة اسم",
    namePlaceholder: "ادخل اسم الموظف كاملاً",
    deleteName: "حذف",
    dictionaryEmpty: "القاموس فارغ. أضف أسماء الموظفين لضمان دقة أعلى.",
    nameExists: "هذا الاسم موجود بالفعل",
    userManagement: "إدارة المستخدمين",
    manageUsersSubtitle: "إنشاء وتعديل حسابات الموظفين وصلاحياتهم",
    addUser: "إضافة مستخدم جديد",
    userName: "اسم المستخدم",
    role: "الصلاحية",
    admin: "مسؤول",
    hrUser: "موظف HR",
    saveDatabase: "حفظ قاعدة البيانات",
    importDatabase: "استيراد قاعدة بيانات",
    dbRequired: "يرجى تحميل ملف قاعدة البيانات (.json) للبدء",
    newDatabase: "إنشاء قاعدة بيانات جديدة",
    dbLoaded: "تم تحميل قاعدة البيانات بنجاح",
    invalidLogin: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    noDbFile: "لم يتم العثور على ملف قاعدة البيانات",
    selectYear: "اختر السنة",
    yearPlaceholder: "السنة المالية للكشف",
    titleWithYear: "الكشف لسنة",
    saturdayFirst: "تنبيه: الكشف يبدأ من السبت على اليمين",
    visualDictionary: "نماذج الأرقام",
    visualDictionarySubtitle: "رفع عينات من الأرقام المكتوبة بخط اليد لتدريب النظام",
    addSample: "إضافة عينة",
    digitValue: "قيمة الرقم",
    noSamples: "لا توجد عينات بعد. ارفع قصاصات من الأرقام لزيادة الدقة."
  },
  en: {
    title: "Handwritten Attendance Converter",
    subtitle: "Convert handwritten attendance sheets to smart Excel files",
    login: "Login",
    email: "Email",
    password: "Password",
    upload: "Upload File",
    dashboard: "Dashboard",
    status: "Status",
    date: "Date",
    uploadedBy: "Uploaded By",
    actions: "Actions",
    processing: "Processing",
    completed: "Completed",
    failed: "Failed",
    noFiles: "No files uploaded yet",
    dragDrop: "Drag & drop files here or click to select",
    maxSize: "Max file size: 20MB",
    convertToDigital: "Convert to Digital",
    reviewEdit: "Review & Edit Data",
    downloadExcel: "Download Excel",
    employeeName: "Employee Name",
    checkIn: "Check-in",
    checkOut: "Check-out",
    saveChanges: "Save Changes",
    confidenceInfo: "Cells highlighted in red mean low confidence, please review.",
    arabicDigits: "Arabic Digits",
    englishInterface: "English Interface",
    arabicInterface: "واجهة عربية",
    manageDictionary: "Name Dictionary",
    dictionarySubtitle: "Add employee names to improve OCR recognition accuracy",
    addName: "Add Name",
    namePlaceholder: "Enter full employee name",
    deleteName: "Delete",
    dictionaryEmpty: "Dictionary is empty. Add names to ensure higher accuracy.",
    nameExists: "This name already exists",
    userManagement: "User Management",
    manageUsersSubtitle: "Create and manage employee accounts and permissions",
    addUser: "Add New User",
    userName: "User Name",
    role: "Role",
    admin: "Administrator",
    hrUser: "HR User",
    saveDatabase: "Save Database File",
    importDatabase: "Import Database",
    dbRequired: "Please upload a database file (.json) to continue",
    newDatabase: "Create New Database",
    dbLoaded: "Database loaded successfully",
    invalidLogin: "Invalid email or password",
    noDbFile: "No database file found",
    selectYear: "Select Year",
    yearPlaceholder: "Fiscal Year of sheet",
    titleWithYear: "Sheet Year",
    saturdayFirst: "Note: Sheet starts from Saturday on the right",
    visualDictionary: "Number Samples",
    visualDictionarySubtitle: "Upload snippets of handwritten numbers to train the system",
    addSample: "Add Sample",
    digitValue: "Digit Value",
    noSamples: "No samples yet. Upload snippets of numbers to increase accuracy."
  }
};

export const COLORS = {
  primary: 'blue-600',
  secondary: 'gray-600',
  success: 'green-500',
  danger: 'red-500',
  warning: 'yellow-500',
};
