
export const TRANSLATIONS = {
  ar: {
    title: "محول كشوف الحضور اليدوية",
    subtitle: "تحويل كشوف الحضور المكتوبة بخط اليد إلى ملفات Excel ذكية",
    login: "تسجيل الدخول",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    upload: "رفع ملف",
    dashboard: "لوحة التحكم",
    status: "الحالة",
    date: "التاريخ",
    uploadedBy: "رفع بواسطة",
    actions: "الإجراءات",
    processing: "جاري المعالجة",
    completed: "مكتمل",
    failed: "فشل",
    noFiles: "لا يوجد ملفات مرفوعة بعد",
    dragDrop: "اسحب وأفلت الملف هنا أو انقر للاختيار",
    maxSize: "الحد الأقصى للملف: 20 ميجابايت",
    convertToDigital: "تحويل إلى بيانات رقمية",
    reviewEdit: "مراجعة وتعديل البيانات",
    downloadExcel: "تحميل ملف Excel",
    employeeName: "اسم الموظف",
    checkIn: "حضور",
    checkOut: "انصراف",
    saveChanges: "حفظ التعديلات",
    confidenceInfo: "الخلايا المظللة بالأحمر تعني دقة منخفضة، يرجى مراجعتها.",
    arabicDigits: "الأرقام العربية",
    englishInterface: "English Interface",
    arabicInterface: "واجهة عربية",
    manageDictionary: "قاموس الأسماء",
    dictionarySubtitle: "إضافة أسماء الموظفين لتحسين دقة التعرف الضوئي (OCR)",
    addName: "إضافة اسم",
    namePlaceholder: "ادخل اسم الموظف كاملاً",
    deleteName: "حذف",
    dictionaryEmpty: "القاموس فارغ. أضف أسماء الموظفين لضمان دقة أعلى.",
    nameExists: "هذا الاسم موجود بالفعل",
    userManagement: "إدارة المستخدمين",
    manageUsersSubtitle: "إنشاء وتعديل حسابات الموظفين وصلاحياتهم",
    addUser: "إضافة مستخدم جديد",
    editUser: "تعديل مستخدم",
    userName: "اسم المستخدم",
    role: "الصلاحية",
    admin: "مسؤول",
    hrUser: "موظف HR",
    saveDatabase: "حفظ / مزامنة الملف",
    importDatabase: "الاتصال بملف قاعدة بيانات",
    dbRequired: "يرجى ربط ملف قاعدة البيانات (.json) للبدء",
    newDatabase: "إنشاء قاعدة بيانات جديدة",
    dbLoaded: "تم تحميل الملف بنجاح",
    dbConnectedSuccess: "تم الاتصال بقاعدة البيانات بنجاح",
    invalidLogin: "خطأ في الدخول",
    invalidLoginMsg: "البريد الإلكتروني أو كلمة المرور غير صحيحة. يرجى المحاولة مرة أخرى.",
    noDbFile: "لم يتم العثور على ملف قاعدة البيانات",
    selectYear: "اختر السنة",
    yearPlaceholder: "السنة المالية للكشف",
    titleWithYear: "الكشف لسنة",
    saturdayFirst: "تنبيه: الكشف يبدأ من السبت على اليمين",
    visualDictionary: "نماذج الأرقام",
    visualDictionarySubtitle: "رفع عينات من الأرقام المكتوبة بخط اليد لتدريب النظام",
    addSample: "إضافة عينة",
    digitValue: "قيمة الرقم",
    noSamples: "لا توجد عينات بعد. ارفع قصاصات من الأرقام لزيادة الدقة.",
    deleteFile: "حذف الملف",
    confirmDelete: "هل أنت متأكد من الحذف؟",
    cancel: "إلغاء",
    edit: "تعديل",
    switchDb: "تغيير الملف",
    syncManual: "تحميل التحديثات يدوياً",
    browserRestricted: "بيئة المتصفح مقيدة. سيتم استخدام الذاكرة المحلية والرفع اليدوي.",
    chooseFile: "اختر ملف .json من جهازك",
    localMode: "وضع المتصفح المحلي (سيتم الحفظ عند النقر على أيقونة الحفظ)",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    optional: "اختياري",
    learningFromCorrections: "التعلم من التعديلات",
    dateRangeHelp: "تحديد التواريخ يساعد النظام على مطابقة الأيام بدقة أعلى",
    storageMode: "وضع التخزين",
    localFile: "ملف محلي (.json)",
    firebaseCloud: "سحابة Firebase (مزامنة تلقائية)",
    signInWithGoogle: "تسجيل الدخول بواسطة Google",
    firebaseError: "خطأ في Firebase",
    importToCloud: "استيراد بيانات محلية للسحابة",
    importToCloudHelp: "اختر ملف attendance_db.json لرفعه إلى حسابك السحابي",
    signUp: "إنشاء حساب",
    or: "أو",
    home: "الرئيسية",
    features: "المميزات",
    howItWorks: "كيف يعمل",
    contactUs: "اتصل بنا",
    getStarted: "ابدأ الآن",
    signIn: "دخول",
    heroTitle: "أتمتة حضور الموظفين المكتوب بخط اليد",
    heroSubtitle: "حول كشوف الحضور اليدوية المعقدة إلى سجلات رقمية منظمة بدقة 99٪ باستخدام الذكاء الاصطناعي المتقدم.",
    startForFree: "ابدأ مجاناً",
    signInToDashboard: "الدخول للوحة التحكم",
    featuresTitle: "كل ما تحتاجه لرقمنة الحضور",
    featuresSubtitle: "توقف عن إدخال البيانات يدوياً ودع الذكاء الاصطناعي يقوم بالعمل الشاق.",
    easyUpload: "رفع سهل",
    easyUploadDesc: "ببساطة ارفع صوراً أو مسحاً ضوئياً لكشوف الحضور. نحن نتعامل مع الصور المائلة والإضاءة السيئة تلقائياً.",
    smartOCR: "تعرف ضوئي ذكي (OCR)",
    smartOCRDesc: "محركنا يستخدم نماذج متعددة لقراءة الأسماء العربية المكتوبة بخط اليد والأرقام المختلطة بدقة.",
    fuzzyMatching: "مطابقة مرنة",
    fuzzyMatchingDesc: "يطابق الأسماء التي تم التعرف عليها تلقائياً مع قاعدة بيانات موظفيك للتخلص من الأخطاء الإملائية.",
    howItWorksTitle: "كيف يعمل النظام",
    howItWorksSubtitle: "حول عملية الحضور اليدوية إلى عملية رقمية في أربع خطوات بسيطة.",
    step1Title: "1. رفع الكشوف",
    step1Desc: "التقط صورة أو امسح كشوف الحضور اليدوية وارفعها إلى لوحة التحكم.",
    step2Title: "2. معالجة الذكاء الاصطناعي",
    step2Desc: "تحلل نماذجنا المتقدمة خط اليد، وتستخرج الأسماء وأوقات الحضور والانصراف.",
    step3Title: "3. المراجعة والمطابقة",
    step3Desc: "يطابق النظام الأسماء تلقائياً مع قاعدة بياناتك. يمكنك مراجعة وتصحيح أي شكوك بسرعة.",
    step4Title: "4. تصدير البيانات",
    step4Desc: "بمجرد التحقق، قم بتصدير البيانات المنظمة إلى Excel أو CSV للتكامل مع برنامج الرواتب الخاص بك.",
    contactUsTitle: "اتصل بنا",
    contactUsSubtitle: "لديك أسئلة؟ نود أن نسمع منك.",
    sendUsMessage: "أرسل لنا رسالة",
    fillForm: "املأ النموذج أدناه وسيعاود فريقنا الاتصال بك قريباً.",
    name: "الاسم",
    subject: "الموضوع",
    message: "الرسالة",
    sendMessage: "إرسال الرسالة",
    copyright: "© 2026 HandAttend AI. جميع الحقوق محفوظة.",
    termsOfService: "شروط الخدمة",
    privacyPolicy: "سياسة الخصوصية",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الليلي",
    cms: {
      title: "إدارة الموقع (CMS)",
      subtitle: "إنشاء وإدارة صفحات الموقع الإلكتروني العام",
      menuStyle: "نمط القائمة",
      settings: "الإعدادات",
      mediaLibrary: "مكتبة الوسائط",
      newPage: "صفحة جديدة",
      searchPages: "البحث في الصفحات...",
      published: "منشور",
      draft: "مسودة",
      inMenu: "في القائمة",
      blocks: "كتل",
      hideShow: "إخفاء/إظهار",
      duplicate: "تكرار",
      viewLive: "عرض مباشر",
      linkedPages: "الصفحات المرتبطة",
      edit: "تعديل",
      delete: "حذف",
      noPagesFound: "لم يتم العثور على صفحات. انقر على \"صفحة جديدة\" للبدء.",
      deletePageTitle: "حذف الصفحة؟",
      deletePageConfirm: "هل أنت متأكد من حذف \"{title}\"؟ لا يمكن التراجع عن هذا الإجراء.",
      cancel: "إلغاء",
      confirmDelete: "حذف",
      backlinksTitle: "الصفحات التي تشير إلى \"{title}\"",
      backlinksSubtitle: "الروابط الخلفية لـ {slug}",
      noBacklinks: "لا توجد صفحات أخرى تشير إلى هذه الصفحة حالياً.",
      close: "إغلاق",
      previewMode: "وضع المعاينة",
      exitPreview: "خروج من المعاينة",
      editUrl: "تعديل الرابط",
      preview: "معاينة",
      save: "حفظ",
      addBlock: "إضافة كتلة",
      heroSection: "قسم الهيرو (Hero)",
      richText: "نص غني",
      cardsSection: "قسم البطاقات",
      contactForm: "نموذج اتصال",
      newsletter: "النشرة البريدية",
      footer: "التذييل",
      navigationPages: "صفحات التنقل",
      navigationPagesDesc: "اختر الصفحات التي تظهر في قائمة التنقل العامة.",
      backgroundStyle: "نمط الخلفية",
      style: "النمط",
      solid: "لون ثابت",
      gradient: "تدرج لوني",
      transparent: "شفاف",
      glass: "زجاجي (Glass Blur)",
      backgroundColor: "لون الخلفية",
      startColor: "لون البداية",
      endColor: "لون النهاية",
      bottomBorder: "الحد السفلي",
      none: "بدون",
      line: "خط",
      shadow: "ظل",
      stickyHeader: "رأس ثابت (يبقى في الأعلى عند التمرير)",
      menuItemsStyle: "نمط عناصر القائمة",
      textColor: "لون النص",
      hoverColor: "لون التمرير",
      menuButtonStyle: "نمط زر القائمة",
      showSignIn: "إظهار الزر الرئيسي في القائمة",
      buttonText: "نص الزر",
      buttonLink: "رابط الزر",
      borderColor: "لون الحدود",
      hoverEffectColor: "لون التأثير/التمرير",
      logo: "الشعار",
      logoText: "نص الشعار (يظهر عند عدم وجود صورة)",
      logoImageUrl: "رابط صورة الشعار",
      upload: "رفع",
      uploadFile: "رفع ملف",
      chooseFromLibrary: "مكتبة الوسائط",
      socialIcons: "أيقونات التواصل الاجتماعي",
      showSocialIcons: "إظهار أيقونات التواصل الاجتماعي في الرأس",
      iconsPosition: "موقع الأيقونات",
      left: "يسار",
      right: "يمين",
      addSocialLink: "+ إضافة رابط تواصل",
      envVars: "متغيرات البيئة ومفاتيح API",
      securityNote: "ملاحظة أمنية: يفضل تخزين مفاتيح API في متغيرات البيئة. المفاتيح المحفوظة هنا يتم تخزينها في قاعدة البيانات.",
      geminiKey: "مفتاح Google Gemini API",
      geminiKeyDesc: "يتجاوز متغير البيئة VITE_GEMINI_API_KEY.",
      socialLinks: "روابط التواصل الاجتماعي",
      deployment: "النشر والاستضافة",
      deploymentDesc: "لنشر هذا الموقع على Vercel أو Netlify أو GitHub Pages، يجب عليك رفع الكود إلى مستودع GitHub وربطه بمزود الاستضافة الخاص بك.",
      chooseTemplate: "اختر قالباً",
      chooseTemplateDesc: "ابدأ بقالب جاهز أو ابدأ من الصفر",
      availableTemplates: "القوالب المتاحة",
      blankPage: "صفحة فارغة",
      blankPageDesc: "ابدأ بصفحة فارغة وأضف الكتل يدوياً",
      essential: "أساسي",
      saveAllChanges: "حفظ جميع التغييرات",
      saveMenu: "حفظ إعدادات القائمة",
      saveSettings: "حفظ الإعدادات",
      template: "القالب",
      titleLabel: "العنوان",
      titleColor: "لون العنوان",
      titleFont: "خط العنوان",
      showSecondTitle: "إظهار عنوان ثانٍ",
      secondTitle: "العنوان الثاني",
      secondTitleColor: "لون العنوان الثاني",
      secondTitleFont: "خط العنوان الثاني",
      subtitleLabel: "العنوان الفرعي",
      subtitleColor: "لون العنوان الفرعي",
      buttonBgColor: "خلفية الزر",
      buttonTextColor: "لون نص الزر",
      showSecondButton: "إظهار زر ثانٍ",
      secondButtonText: "نص الزر الثاني",
      secondButtonLink: "رابط الزر الثاني",
      secondButtonBgColor: "خلفية الزر الثاني",
      secondButtonTextColor: "لون نص الزر الثاني",
      backgroundImage: "صورة الخلفية",
      imageGuideSplit: "الحجم الموصى به: 1200×900 بكسل (نسبة أبعاد 4:3)",
      imageGuideFull: "الحجم الموصى به: 1920×1080 بكسل (نسبة أبعاد 16:9)",
      contentHtml: "المحتوى (يدعم HTML)",
      placeholderHtml: "أدخل محتوى النص الغني (يدعم HTML حالياً)...",
      sectionHeading: "عنوان القسم",
      columns: "الأعمدة",
      cols: "أعمدة",
      cards: "البطاقات",
      card: "بطاقة",
      iconName: "اسم الأيقونة (مثلاً Zap)",
      description: "الوصف",
      addCard: "+ إضافة بطاقة",
      formTitle: "عنوان النموذج",
      formSubtitle: "العنوان الفرعي للنموذج",
      formFields: "حقول النموذج",
      field: "حقل",
      label: "التسمية",
      type: "النوع",
      requiredField: "حقل مطلوب",
      addField: "+ إضافة حقل",
      placeholderText: "نص تلميحي",
      companyName: "اسم الشركة",
      copyrightText: "نص حقوق النشر",
      saveMenuSettings: "حفظ إعدادات القائمة",
      glassBlur: "تغبيش زجاجي (Glass Blur)",
      buttonStyle: "نمط الزر",
      socialMediaIcons: "أيقونات التواصل الاجتماعي",
      deploymentHosting: "النشر والاستضافة",
      deploymentHostingDesc: "لنشر هذا الموقع على Vercel أو Netlify أو GitHub Pages، يجب عليك رفع الكود إلى مستودع GitHub وربطه بمزود الاستضافة الخاص بك.",
      vercelDesc: "قم باستيراد مستودع GitHub الخاص بك في لوحة تحكم Vercel. سيتعرف تلقائياً على Vite ويقوم بتكوين إعدادات البناء.",
      netlifyDesc: "قم باستيراد مستودع GitHub الخاص بك في لوحة تحكم Netlify. ملف netlify.toml مهيأ بالفعل لتوجيه SPA.",
      envVarsDesc: "تذكر إضافة VITE_GEMINI_API_KEY ومتغيرات تكوين Firebase في إعدادات مزود الاستضافة الخاص بك.",
      liveUrl: "الرابط المباشر",
      geminiApiKey: "مفتاح Google Gemini API",
      geminiApiKeyOverride: "يتجاوز متغير البيئة VITE_GEMINI_API_KEY.",
      envVarsApiKeys: "متغيرات البيئة ومفاتيح API",
      securityNoteDesc: "يجب تخزين مفاتيح API بشكل مثالي في متغيرات البيئة (مثل Vercel أو Netlify أو GitHub Secrets). المفاتيح المحفوظة هنا يتم تخزينها في قاعدة البيانات وقد يتم كشفها للكود من جانب العميل حسب الاستخدام.",
    },
  },
  en: {
    title: "Handwritten Attendance Converter",
    subtitle: "Convert handwritten attendance sheets to smart Excel files",
    login: "Login",
    email: "Email",
    password: "Password",
    upload: "Upload File",
    dashboard: "Dashboard",
    status: "Status",
    date: "Date",
    uploadedBy: "Uploaded By",
    actions: "Actions",
    processing: "Processing",
    completed: "Completed",
    failed: "Failed",
    noFiles: "No files uploaded yet",
    dragDrop: "Drag & drop files here or click to select",
    maxSize: "Max file size: 20MB",
    convertToDigital: "Convert to Digital",
    reviewEdit: "Review & Edit Data",
    downloadExcel: "Download Excel",
    employeeName: "Employee Name",
    checkIn: "Check-in",
    checkOut: "Check-out",
    saveChanges: "Save Changes",
    confidenceInfo: "Cells highlighted in red mean low confidence, please review.",
    arabicDigits: "Arabic Digits",
    englishInterface: "English Interface",
    arabicInterface: "واجهة عربية",
    manageDictionary: "Name Dictionary",
    dictionarySubtitle: "Add employee names to improve OCR recognition accuracy",
    howItWorks: "How it Works",
    contactUs: "Contact Us",
    getStarted: "Get Started",
    signIn: "Sign In",
    heroTitle: "Automate Arabic Handwritten Attendance",
    heroSubtitle: "Convert messy, handwritten Arabic attendance sheets into structured digital records with 99% accuracy using advanced AI and OCR.",
    startForFree: "Start for free",
    signInToDashboard: "Sign In to Dashboard",
    featuresTitle: "Everything you need to digitize attendance",
    featuresSubtitle: "Stop manual data entry and let AI do the heavy lifting.",
    easyUpload: "Easy Upload",
    easyUploadDesc: "Simply upload photos or scans of your attendance sheets. We handle skewed images and bad lighting automatically.",
    smartOCR: "Smart Arabic OCR",
    smartOCRDesc: "Our consensus engine uses multiple OCR models to accurately read cursive Arabic names and mixed numerals.",
    fuzzyMatching: "Fuzzy Matching",
    fuzzyMatchingDesc: "Automatically matches recognized names to your employee database to eliminate typos and ensure clean data.",
    howItWorksTitle: "How It Works",
    howItWorksSubtitle: "Transform your manual attendance process in four simple steps.",
    step1Title: "1. Upload Sheets",
    step1Desc: "Take a photo or scan your handwritten Arabic attendance sheets and upload them to the dashboard.",
    step2Title: "2. AI Processing",
    step2Desc: "Our advanced AI models analyze the handwriting, extracting names, arrival times, and departure times.",
    step3Title: "3. Review & Match",
    step3Desc: "The system automatically matches names to your employee database. You can quickly review and correct any uncertainties.",
    step4Title: "4. Export Data",
    step4Desc: "Once verified, export the structured data to Excel or CSV for seamless integration with your payroll software.",
    contactUsTitle: "Contact Us",
    contactUsSubtitle: "Have questions? We'd love to hear from you.",
    sendUsMessage: "Send us a message",
    fillForm: "Fill out the form below and our team will get back to you shortly.",
    name: "Name",
    subject: "Subject",
    message: "Message",
    sendMessage: "Send Message",
    copyright: "© 2026 HandAttend AI. All rights reserved.",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    addName: "Add Name",
    namePlaceholder: "Enter full employee name",
    deleteName: "Delete",
    dictionaryEmpty: "Dictionary is empty. Add names to ensure higher accuracy.",
    nameExists: "This name already exists",
    userManagement: "User Management",
    manageUsersSubtitle: "Create and manage employee accounts and permissions",
    addUser: "Add New User",
    editUser: "Edit User",
    userName: "User Name",
    role: "Role",
    admin: "Administrator",
    hrUser: "HR User",
    saveDatabase: "Save / Sync File",
    importDatabase: "Connect Database File",
    dbRequired: "Please connect a database file (.json) to start",
    newDatabase: "Create New Database",
    dbLoaded: "File loaded successfully",
    dbConnectedSuccess: "Database connected successfully",
    invalidLogin: "Login Error",
    invalidLoginMsg: "Invalid email or password. Please try again.",
    noDbFile: "No database file found",
    selectYear: "Select Year",
    yearPlaceholder: "Fiscal Year of sheet",
    titleWithYear: "Sheet Year",
    saturdayFirst: "Note: Sheet starts from Saturday on the right",
    visualDictionary: "Number Samples",
    visualDictionarySubtitle: "Upload snippets of handwritten numbers to train the system",
    addSample: "Add Sample",
    digitValue: "Digit Value",
    noSamples: "No samples yet. Upload snippets of numbers to increase accuracy.",
    deleteFile: "Delete File",
    confirmDelete: "Are you sure you want to delete this?",
    cancel: "Cancel",
    edit: "Edit",
    switchDb: "Switch File",
    syncManual: "Download Updates Manually",
    browserRestricted: "Browser environment is restricted. Using local storage mode.",
    chooseFile: "Choose .json file from device",
    localMode: "Local Browser Mode (Save manually via the icon)",
    startDate: "Start Date",
    endDate: "End Date",
    optional: "Optional",
    learningFromCorrections: "Learning from corrections",
    dateRangeHelp: "Specifying dates helps the system match days with higher accuracy",
    storageMode: "Storage Mode",
    localFile: "Local File (.json)",
    firebaseCloud: "Firebase Cloud (Auto-sync)",
    signInWithGoogle: "Sign in with Google",
    firebaseError: "Firebase Error",
    importToCloud: "Import Local Data to Cloud",
    importToCloudHelp: "Select your attendance_db.json file to upload it to your cloud account",
    signUp: "Sign Up",
    or: "OR",
    cms: {
      title: "Website CMS",
      subtitle: "Create and manage public-facing website pages",
      menuStyle: "Menu Style",
      settings: "Settings",
      mediaLibrary: "Media Library",
      newPage: "New Page",
      searchPages: "Search pages...",
      published: "Published",
      draft: "Draft",
      inMenu: "In Menu",
      blocks: "blocks",
      hideShow: "Hide/Show",
      duplicate: "Duplicate",
      viewLive: "View Live",
      linkedPages: "Linked Pages",
      edit: "Edit",
      delete: "Delete",
      noPagesFound: "No pages found. Click \"New Page\" to get started.",
      deletePageTitle: "Delete Page?",
      deletePageConfirm: "Are you sure you want to delete \"{title}\"? This action cannot be undone.",
      cancel: "Cancel",
      confirmDelete: "Delete",
      backlinksTitle: "Pages linking to \"{title}\"",
      backlinksSubtitle: "Backlinks for {slug}",
      noBacklinks: "No other pages are currently linking to this page.",
      close: "Close",
      previewMode: "Preview Mode",
      exitPreview: "Exit Preview",
      editUrl: "Edit URL",
      preview: "Preview",
      save: "Save",
      addBlock: "Add Block",
      heroSection: "Hero Section",
      richText: "Rich Text",
      cardsSection: "Cards Section",
      contactForm: "Contact Form",
      newsletter: "Newsletter",
      footer: "Footer",
      navigationPages: "Navigation Pages",
      navigationPagesDesc: "Toggle which pages appear in the public navigation menu.",
      backgroundStyle: "Background Style",
      style: "Style",
      solid: "Solid",
      gradient: "Gradient",
      transparent: "Transparent",
      glass: "Glass Blur",
      backgroundColor: "Background Color",
      startColor: "Start Color",
      endColor: "End Color",
      bottomBorder: "Bottom Border",
      none: "None",
      line: "Line",
      shadow: "Shadow",
      stickyHeader: "Sticky header (stays on top when scrolling)",
      menuItemsStyle: "Menu Items Style",
      textColor: "Text Color",
      hoverColor: "Hover Color",
      menuButtonStyle: "Menu Button Style",
      showSignIn: "Show primary button in menu",
      buttonText: "Button Text",
      buttonLink: "Button Link",
      borderColor: "Border Color",
      hoverEffectColor: "Hover/Effect Color",
      logo: "Logo",
      logoText: "Logo Text (shown when no image)",
      logoImageUrl: "Logo Image URL",
      upload: "Upload",
      uploadFile: "Upload File",
      chooseFromLibrary: "Media Library",
      socialIcons: "Social Media Icons",
      showSocialIcons: "Show social media icons in header",
      iconsPosition: "Icons Position",
      left: "Left",
      right: "Right",
      addSocialLink: "+ Add Social Link",
      envVars: "Environment Variables & API Keys",
      securityNote: "Security Note: API keys should ideally be stored in environment variables. Keys saved here are stored in the database.",
      geminiKey: "Google Gemini API Key",
      geminiKeyDesc: "Overrides the VITE_GEMINI_API_KEY environment variable.",
      socialLinks: "Social Media Links",
      deployment: "Deployment & Hosting",
      deploymentDesc: "To deploy this website to Vercel, Netlify, or GitHub Pages, you should commit your code to a GitHub repository and connect it to your hosting provider.",
      chooseTemplate: "Choose a Template",
      chooseTemplateDesc: "Start with a pre-built template or begin from scratch",
      availableTemplates: "Available Templates",
      blankPage: "Blank Page",
      blankPageDesc: "Start with an empty page and add blocks manually",
      essential: "Essential",
      saveAllChanges: "Save All Changes",
      saveMenu: "Save Menu Settings",
      saveSettings: "Save Settings",
      template: "Template",
      titleLabel: "Title",
      titleColor: "Title Color",
      titleFont: "Title Font",
      showSecondTitle: "Show Second Title",
      secondTitle: "Second Title",
      secondTitleColor: "Second Title Color",
      secondTitleFont: "Second Title Font",
      subtitleLabel: "Subtitle",
      subtitleColor: "Subtitle Color",
      buttonBgColor: "Button Background",
      buttonTextColor: "Button Text Color",
      showSecondButton: "Show Second Button",
      secondButtonText: "Second Button Text",
      secondButtonLink: "Second Button Link",
      secondButtonBgColor: "Second Button Background",
      secondButtonTextColor: "Second Button Text Color",
      backgroundImage: "Background Image",
      imageGuideSplit: "Recommended size: 1200x900 pixels (4:3 aspect ratio)",
      imageGuideFull: "Recommended size: 1920x1080 pixels (16:9 aspect ratio)",
      contentHtml: "Content (HTML supported)",
      placeholderHtml: "Enter rich text content (HTML supported for now)...",
      sectionHeading: "Section Heading",
      columns: "Columns",
      cols: "cols",
      cards: "Cards",
      card: "Card",
      iconName: "Icon name (e.g. Zap)",
      description: "Description",
      addCard: "+ Add Card",
      formTitle: "Form Title",
      formSubtitle: "Form Subtitle",
      formFields: "Form Fields",
      field: "Field",
      label: "Label",
      type: "Type",
      requiredField: "Required field",
      addField: "+ Add Field",
      placeholderText: "Placeholder Text",
      companyName: "Company Name",
      copyrightText: "Copyright Text",
      saveMenuSettings: "Save Menu Settings",
      glassBlur: "Glass Blur",
      buttonStyle: "Button Style",
      socialMediaIcons: "Social Media Icons",
      deploymentHosting: "Deployment & Hosting",
      deploymentHostingDesc: "To deploy this website to Vercel, Netlify, or GitHub Pages, you should commit your code to a GitHub repository and connect it to your hosting provider.",
      vercelDesc: "Import your GitHub repository in the Vercel dashboard. It will automatically detect Vite and configure the build settings.",
      netlifyDesc: "Import your GitHub repository in the Netlify dashboard. The netlify.toml file is already configured for SPA routing.",
      envVarsDesc: "Remember to add your VITE_GEMINI_API_KEY and Firebase configuration variables in your hosting provider's settings.",
      liveUrl: "Live URL",
      geminiApiKey: "Google Gemini API Key",
      geminiApiKeyOverride: "Overrides the VITE_GEMINI_API_KEY environment variable.",
      envVarsApiKeys: "Environment Variables & API Keys",
      securityNoteDesc: "API keys should ideally be stored in environment variables (e.g., Vercel, Netlify, GitHub Secrets). Keys saved here are stored in the database and may be exposed to client-side code depending on usage.",
    },
  }
};

export const COLORS = {
  primary: 'blue-600',
  secondary: 'gray-600',
  success: 'green-500',
  danger: 'red-500',
  warning: 'yellow-500',
};
